name: Python Flask App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch
          pip install xgboost
          pip install pytorch-tabnet
          pip install pennylane
          pip install flask
          pip install joblib
          pip install numpy pandas

      - name: Check model files exist
        run: |
          test -f models/tabnet_model.pt || echo "Missing: tabnet_model.pt"
          test -f models/vqc_model.pkl || echo "Missing: vqc_model.pkl"
          test -f models/qnn_model.npz || echo "Missing: qnn_model.npz"
          test -f models/xgboost_model.json || echo "Missing: xgboost_model.json"

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
